[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "9Xj8xEXWKfoBfDJGXEM8nFu44M1s2jJvSmCeVgNR3nae"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/rohits/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
